pub mod account_store;
pub mod activity_store;
mod calendar;
pub mod cli;
pub mod commands;
mod credential_store;
mod disk;
mod disk_link;
pub mod doctor;
pub mod error;
pub mod goal_router;
pub mod home;
mod mail;
mod mail_link;
pub mod mcp;
pub mod model;
pub mod next_actions;
mod oauth;
pub mod onboarding;
pub mod output;
pub mod paths;
mod persist;
pub mod runtime_context;
pub mod update;
pub mod workflows;
